### ISSUE TITLE
Can't run test.py on AGX Xavier

### ISSUE THREAD

**Issue by smezac29** [sskorol/vosk-api-gpu#6]
Hi, first of all, thank you for making this open-source, it is really helpful. I recently followed the steps to build vosk with GPU support on my Nvidia AGX Xavier, but after running **./test.py weather.wav** I run into this error:

Traceback (most recent call last):
  File "./test.py", line 23, in <module>
    run_test('ws://localhost:2700'))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "./test.py", line 8, in run_test
    async with websockets.connect(uri) as websocket:
  File "/home/xbio/.local/lib/python3.6/site-packages/websockets/legacy/client.py", line 604, in __aenter__
    return await self
  File "/home/xbio/.local/lib/python3.6/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 2700)

About my system:
OS: Linux 18.04
CUDA Version: 10.2

I used the **docker pull sskorol/vosk-api:0.3.30-xavier** command to pull the image. 
After that, I used **./build.sh -m xavier -i base -l r32.6.1 -t 0.3.30**
and installed the dependencies: **pip3 install websockets asyncio**

Everything until there was fine, I hit the problem when trying to run the test, any comments on this? 

I'm new to Vosk and all the help would be really appreciated. I'm really trying to figure out if I can implement speech recognition faster into my code. My idea is to use a camera and control it using a USB microphone. I already achieved this using Vosk (which I built normally, not using GPU), the problem is that it slowed down my code so much that I couldn't even read frames from my camera anymore. 

I would also appreciate it if you could provide some guidance on how can I implement your docker images/code into my python code and if needed I can provide the script I'm using right now for speech recognition. 

Thanks!

**Comment by sskorol** [comment]
You don't need to do both pulling and building. These are 2 different strategies for running this example. 

You should pull an existing image only if you want to avoid manual building and run your own code based on Vosk API. 

Building section is for the cases when your hardware or software versions are incompatible with the existing image.

Let's say you built your own image with a script. That's fine. But it's just a base image with Vosk package installed. You still have to build your own container with a server code the way how it's done for PC version for example.

Anyway, your error says the server is not running. From your commands I don't see you have started it. Pulling or building a Docker image != running it. So I'd recommend reading some Docker basics first before you proceed.

Of course I can create an image with a server for Xavier as well, but you still need to get familiar with Docker first. Otherwise, you will fail running and understanding some basic steps.

BTW, this setup was initially designed for Nano and Xavier NX. Not sure if all the build flags will be the same for your version. Can you double-check?

**Comment by smezac29** [comment]
Thanks for the explanation! 
From the Nvidia webpage, the AGX Xavier has the following specs:

**CPU:** 8-core ARM v8.2 64-bit CPU, 8MB L2 + 4MB L3, does this mean that the arch = armv8.2 and cpu=cortex a-76?

And regarding Vosk performance, I have been using the small US-English model **vosk-model-small-en-us-0.15**, maybe if I use a different model (or instead of using the latest vosk version I use an older Vosk version) the performance will be better on the AGX?

**Comment by sskorol** [comment]
Well, a small model should work pretty fast.
If you've already built an api image, you can now bundle it with a server. Just build a new image on top of it via the following Dockerfile:
```
ARG TAG=0.3.30

FROM sskorol/vosk-api:$TAG

RUN mkdir /opt/vosk-server
COPY ./asr_server.py /opt/vosk-server
RUN python3 -m pip install --upgrade pip
RUN pip3 install websockets asyncio

EXPOSE 2700
WORKDIR /opt/vosk-server

CMD ["python3", "./asr_server.py"]
```
Then start it via the existing `docker-compose.yml`. But don't forget to change the image to the newly built reference. Now you can run the example.

**Comment by sskorol** [comment]
Closing due to inactivity. Feel free to reopen.
